#!/usr/bin/env python3
"""PreToolUse guard: enforce the rules a machine can check, generated by rule-architect.

This file is copied into a project as `.claude/hooks/rule_guard.py` by
`hookgen.py`. It is generic: every project-specific detail lives in
`.rule-architect/hooks.json`, so the guard itself never needs regenerating.

Two rule shapes:

  forbid — a regex matched against the text a tool call would WRITE
  deny   — a path that a listed tool may not touch at all (no regex)

Contract with the harness: read the PreToolUse payload on stdin; exit 2 with a
message on stderr to block the call and tell the agent why; exit 0 to allow.

Fail open, always. A guard that crashes must not stop the work — a broken
enforcement is a bug in the rules, not a reason to wedge the session.
"""
import fnmatch
import json
import os
import re
import sys
from pathlib import Path

SPEC_REL = Path('.rule-architect') / 'hooks.json'
WRITE_TOOLS = ('Edit', 'Write', 'MultiEdit', 'NotebookEdit')
READ_TOOLS = ('Read', 'Grep', 'Glob')


def projectRoot():
    return Path(os.environ.get('CLAUDE_PROJECT_DIR') or Path.cwd()).resolve()


# Glob match on the project-relative path. fnmatch alone treats `*` as crossing
# directories, so `**/` is expanded explicitly and `*` kept inside one segment.
def matchesGlob(relative, glob):
    pattern = re.escape(glob).replace(r'\*\*/', '(?:.*/)?').replace(
        r'\*\*', '.*').replace(r'\*', '[^/]*').replace(r'\?', '[^/]')
    if re.fullmatch(pattern, relative):
        return True
    if fnmatch.fnmatch(relative, glob):
        return True
    # a directory prefix ("docs/", "docs/**") covers everything under it
    bare = glob[:-3] if glob.endswith('/**') else glob
    return bool(bare) and (relative == bare.rstrip('/')
                           or relative.startswith(bare.rstrip('/') + '/'))


# Every piece of text this tool call would write into the file
def writtenText(toolName, toolInput):
    if toolName == 'MultiEdit':
        edits = toolInput.get('edits') or []
        return '\n'.join(str(edit.get('new_string', '')) for edit in edits
                         if isinstance(edit, dict))
    for key in ('content', 'new_string', 'new_source'):
        if key in toolInput:
            return str(toolInput[key] or '')
    return ''


# The paths this call would touch, project-relative. Grep and Glob carry a
# search root rather than a file, and a search with no path is repo-wide — that
# one cannot be attributed to a directory, so it is not blocked.
def targetPaths(toolInput, root):
    raw = [toolInput.get(key) for key in ('file_path', 'notebook_path', 'path')]
    relatives = []
    for value in raw:
        if not value:
            continue
        candidate = Path(str(value))
        resolved = candidate if candidate.is_absolute() else root / candidate
        try:
            relative = resolved.resolve().relative_to(root).as_posix()
        except ValueError:
            continue  # outside the project — not ours to police
        if relative != '.':
            relatives.append(relative)
    return relatives


def block(rule, relative, detail=''):
    identifier = rule.get('id') or 'rule'
    message = rule.get('message') or 'forbidden by a project rule'
    print(f'BLOCKED [{identifier}] {relative}: {message}'
          + (f'\n  matched: {detail[:120]}' if detail else ''), file=sys.stderr)
    return 2


def main():
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0

    toolName = payload.get('tool_name') or ''
    toolInput = payload.get('tool_input') or {}
    root = projectRoot()
    spec = root / SPEC_REL
    if not spec.is_file():
        return 0
    try:
        rules = json.loads(spec.read_text(encoding='utf-8')).get('rules') or []
    except (OSError, json.JSONDecodeError):
        return 0

    relatives = targetPaths(toolInput, root)
    text = writtenText(toolName, toolInput) if toolName in WRITE_TOOLS else ''

    for rule in rules:
        if not isinstance(rule, dict):
            continue
        glob = str(rule.get('glob') or '')
        if not glob:
            continue
        tools = rule.get('tools')
        if not isinstance(tools, list) or not tools:
            tools = list(WRITE_TOOLS)
        if toolName not in tools:
            continue
        hits = [rel for rel in relatives if matchesGlob(rel, glob)]
        if not hits:
            continue
        if rule.get('deny'):
            return block(rule, hits[0])
        forbid = str(rule.get('forbid') or '')
        if not forbid or not text:
            continue
        try:
            found = re.search(forbid, text)
        except re.error:
            continue
        if found:
            return block(rule, hits[0], found.group(0))
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except Exception:  # fail open — never wedge a session on a guard bug
        sys.exit(0)
