#!/usr/bin/env python3
"""PreToolUse guard: enforce the rules a machine can check, generated by rule-architect.

This file is copied into a project as `.claude/hooks/rule_guard.py` by
`hookgen.py`. It is generic: every project-specific detail lives in
`.rule-architect/hooks.json`, so the guard itself never needs regenerating.

Contract with the harness: read the PreToolUse payload on stdin; exit 2 with a
message on stderr to block the edit and tell the agent why; exit 0 to allow.

Fail open, always. A guard that crashes must not stop the work — a broken
enforcement is a bug in the rules, not a reason to wedge the session.
"""
import fnmatch
import json
import os
import re
import sys
from pathlib import Path

SPEC_REL = Path('.rule-architect') / 'hooks.json'
WRITE_TOOLS = {'Edit', 'Write', 'MultiEdit', 'NotebookEdit'}


def projectRoot():
    return Path(os.environ.get('CLAUDE_PROJECT_DIR') or Path.cwd()).resolve()


# Glob match on the project-relative path. fnmatch alone treats `*` as crossing
# directories, so `**/` is expanded explicitly and `*` kept inside one segment.
def matchesGlob(relative, glob):
    pattern = re.escape(glob).replace(r'\*\*/', '(?:.*/)?').replace(
        r'\*\*', '.*').replace(r'\*', '[^/]*').replace(r'\?', '[^/]')
    if re.fullmatch(pattern, relative):
        return True
    # a bare directory prefix ("src/") covers everything under it
    return glob.endswith('/') and relative.startswith(glob)


# Every piece of text this tool call would write into the file
def writtenText(toolName, toolInput):
    if toolName == 'MultiEdit':
        edits = toolInput.get('edits') or []
        return '\n'.join(str(edit.get('new_string', '')) for edit in edits
                         if isinstance(edit, dict))
    for key in ('content', 'new_string', 'new_source'):
        if key in toolInput:
            return str(toolInput[key] or '')
    return ''


def main():
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0

    toolName = payload.get('tool_name') or ''
    if toolName not in WRITE_TOOLS:
        return 0
    toolInput = payload.get('tool_input') or {}
    rawPath = str(toolInput.get('file_path') or toolInput.get('notebook_path') or '')
    if not rawPath:
        return 0

    root = projectRoot()
    try:
        relative = Path(rawPath).resolve().relative_to(root).as_posix()
    except ValueError:
        return 0  # outside the project — not ours to police

    spec = root / SPEC_REL
    if not spec.is_file():
        return 0
    try:
        rules = json.loads(spec.read_text(encoding='utf-8')).get('rules') or []
    except (OSError, json.JSONDecodeError):
        return 0

    text = writtenText(toolName, toolInput)
    if not text:
        return 0

    for rule in rules:
        if not isinstance(rule, dict):
            continue
        glob = str(rule.get('glob') or '')
        forbid = str(rule.get('forbid') or '')
        if not glob or not forbid:
            continue
        if not (matchesGlob(relative, glob) or fnmatch.fnmatch(relative, glob)):
            continue
        try:
            hit = re.search(forbid, text)
        except re.error:
            continue
        if hit:
            identifier = rule.get('id') or 'rule'
            message = rule.get('message') or 'forbidden by a project rule'
            print(f'BLOCKED [{identifier}] {relative}: {message}\n'
                  f'  matched: {hit.group(0)[:120]}', file=sys.stderr)
            return 2
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except Exception:  # fail open — never wedge a session on a guard bug
        sys.exit(0)
